// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@bw/hello', 0],
  [0, '@bw/hello'],
  ['@bw/ping', 1],
  [1, '@bw/ping'],
  ['@bw/exec', 2],
  [2, '@bw/exec'],
  ['@bw/put', 3],
  [3, '@bw/put'],
  ['@bw/get', 4],
  [4, '@bw/get']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@bw/hello', getEncoding('@bw/hello-request')],
      ['@bw/ping', getEncoding('@bw/ping-request')],
      ['@bw/exec', getEncoding('@bw/exec-request')],
      ['@bw/put', getEncoding('@bw/put-request')],
      ['@bw/get', getEncoding('@bw/get-request')]
    ])
    this._responseEncodings = new Map([
      ['@bw/hello', getEncoding('@bw/hello-response')],
      ['@bw/ping', getEncoding('@bw/ping-response')],
      ['@bw/exec', getEncoding('@bw/exec-response')],
      ['@bw/put', getEncoding('@bw/put-response')],
      ['@bw/get', getEncoding('@bw/get-response')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  async hello(args) {
    return this._call('@bw/hello', args)
  }

  async ping(args) {
    return this._call('@bw/ping', args)
  }

  exec(args) {
    return this._callSync('@bw/exec', args)
  }

  put(args) {
    return this._callSync('@bw/put', args)
  }

  get(args) {
    return this._callSync('@bw/get', args)
  }

  onHello(responseFn) {
    this._handlers['@bw/hello'] = responseFn
  }

  onPing(responseFn) {
    this._handlers['@bw/ping'] = responseFn
  }

  onExec(responseFn) {
    this._handlers['@bw/exec'] = responseFn
  }

  onPut(responseFn) {
    this._handlers['@bw/put'] = responseFn
  }

  onGet(responseFn) {
    this._handlers['@bw/get'] = responseFn
  }

  _requestIsStream(command) {
    return ['@bw/exec', '@bw/put'].includes(command)
  }

  _responseIsStream(command) {
    return ['@bw/exec', '@bw/get'].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
    ].includes(command)
  }
}

module.exports = HRPC
