// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bw/hello-request
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.driver)
  },
  encode(state, m) {
    c.string.encode(state, m.driver)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      driver: r0
    }
  }
}

// @bw/hello-response.strayFds
const encoding1_4 = c.array(c.string)

// @bw/hello-response
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.agent)
    c.string.preencode(state, m.platform)
    c.string.preencode(state, m.arch)
    c.uint.preencode(state, m.pid)
    state.end++ // max flag is 1 so always one byte

    if (m.strayFds) encoding1_4.preencode(state, m.strayFds)
    c.string.preencode(state, m.cwd)
  },
  encode(state, m) {
    const flags = m.strayFds ? 1 : 0

    c.string.encode(state, m.agent)
    c.string.encode(state, m.platform)
    c.string.encode(state, m.arch)
    c.uint.encode(state, m.pid)
    c.uint.encode(state, flags)

    if (m.strayFds) encoding1_4.encode(state, m.strayFds)
    c.string.encode(state, m.cwd)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      agent: r0,
      platform: r1,
      arch: r2,
      pid: r3,
      strayFds: (flags & 1) !== 0 ? encoding1_4.decode(state) : null,
      cwd: c.string.decode(state)
    }
  }
}

// @bw/ping-request
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.nonce)
  },
  encode(state, m) {
    c.uint.encode(state, m.nonce)
  },
  decode(state) {
    const r0 = c.uint.decode(state)

    return {
      nonce: r0
    }
  }
}

// @bw/ping-response
const encoding3 = encoding2

// @bw/exec-request.env
const encoding4_4 = encoding1_4

// @bw/exec-request
const encoding4 = {
  preencode(state, m) {
    c.uint.preencode(state, m.kind)
    state.end++ // max flag is 64 so always one byte

    if (m.run) c.string.preencode(state, m.run)
    if (m.shell) c.string.preencode(state, m.shell)
    if (m.cwd) c.string.preencode(state, m.cwd)
    if (m.env) encoding4_4.preencode(state, m.env)
    if (m.timeoutMs) c.uint.preencode(state, m.timeoutMs)
    if (m.chunk) c.buffer.preencode(state, m.chunk)
    if (m.signal) c.string.preencode(state, m.signal)
  },
  encode(state, m) {
    const flags =
      (m.run ? 1 : 0) |
      (m.shell ? 2 : 0) |
      (m.cwd ? 4 : 0) |
      (m.env ? 8 : 0) |
      (m.timeoutMs ? 16 : 0) |
      (m.chunk ? 32 : 0) |
      (m.signal ? 64 : 0)

    c.uint.encode(state, m.kind)
    c.uint.encode(state, flags)

    if (m.run) c.string.encode(state, m.run)
    if (m.shell) c.string.encode(state, m.shell)
    if (m.cwd) c.string.encode(state, m.cwd)
    if (m.env) encoding4_4.encode(state, m.env)
    if (m.timeoutMs) c.uint.encode(state, m.timeoutMs)
    if (m.chunk) c.buffer.encode(state, m.chunk)
    if (m.signal) c.string.encode(state, m.signal)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      kind: r0,
      run: (flags & 1) !== 0 ? c.string.decode(state) : null,
      shell: (flags & 2) !== 0 ? c.string.decode(state) : null,
      cwd: (flags & 4) !== 0 ? c.string.decode(state) : null,
      env: (flags & 8) !== 0 ? encoding4_4.decode(state) : null,
      timeoutMs: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      chunk: (flags & 32) !== 0 ? c.buffer.decode(state) : null,
      signal: (flags & 64) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bw/exec-response
const encoding5 = {
  preencode(state, m) {
    c.uint.preencode(state, m.kind)
    state.end++ // max flag is 16 so always one byte

    if (m.chunk) c.buffer.preencode(state, m.chunk)
    if (m.code) c.int.preencode(state, m.code)
    if (m.signal) c.string.preencode(state, m.signal)
    if (m.message) c.string.preencode(state, m.message)
  },
  encode(state, m) {
    const flags =
      (m.chunk ? 1 : 0) |
      (m.code ? 2 : 0) |
      (m.signal ? 4 : 0) |
      (m.message ? 8 : 0) |
      (m.timedOut ? 16 : 0)

    c.uint.encode(state, m.kind)
    c.uint.encode(state, flags)

    if (m.chunk) c.buffer.encode(state, m.chunk)
    if (m.code) c.int.encode(state, m.code)
    if (m.signal) c.string.encode(state, m.signal)
    if (m.message) c.string.encode(state, m.message)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      kind: r0,
      chunk: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      code: (flags & 2) !== 0 ? c.int.decode(state) : 0,
      signal: (flags & 4) !== 0 ? c.string.decode(state) : null,
      message: (flags & 8) !== 0 ? c.string.decode(state) : null,
      timedOut: (flags & 16) !== 0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@bw/hello-request':
      return encoding0
    case '@bw/hello-response':
      return encoding1
    case '@bw/ping-request':
      return encoding2
    case '@bw/ping-response':
      return encoding3
    case '@bw/exec-request':
      return encoding4
    case '@bw/exec-response':
      return encoding5
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
